### ISSUE TITLE
map null data from postgres got panic

### ISSUE THREAD

**Issue by Lan-Phan** [illacloud/builder-backend#128]
Hello,

I'm using illa-builder to query data from postgres db. The problem here is my query can produce nil data in some columns, and it causes panic here:

```
2023/02/17 01:26:15 [Recovery] 2023/02/17 - 01:26:15 panic recovered:
reflect: New(nil)
/usr/local/go/src/reflect/value.go:3086 (0x4a150c)
/opt/illa/builder-backend/pkg/plugins/postgresql/base.go:148 (0x1645d64)
	RetrieveToMap: valuePtrs[i] = reflect.New(reflect.TypeOf(v)).Interface() // allocate pointer to type
/opt/illa/builder-backend/pkg/plugins/postgresql/service.go:132 (0x16467e7)
	(*Connector).Run: mapRes, err := RetrieveToMap(rows)
/opt/illa/builder-backend/pkg/action/service.go:254 (0x1c69ef2)
	(*ActionServiceImpl).RunAction: res, err := actionAssemblyLine.Run(rsc.Options, action.Template)
/opt/illa/builder-backend/api/resthandler/action.go:275 (0x1c7b7fc)
	ActionRestHandlerImpl.RunAction: res, err := impl.actionService.RunAction(act)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0x1c76bda)
/opt/illa/builder-backend/pkg/user/middleware.go:41 (0x1c76bbe)
	JWTAuth.func1: c.Next()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0x1c8bcdd)
/opt/illa/builder-backend/pkg/cors/middleware.go:36 (0x1c8bcc9)
	Cors.func1: c.Next()
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0x943821)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101 (0x94380c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0x942690)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616 (0x9422f8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572 (0x941e3c)
/usr/local/go/src/net/http/server.go:2947 (0x6f1b2b)
/usr/local/go/src/net/http/server.go:1991 (0x6ecd46)
```

Would you please review and take care of this case?

Thanks.

**Comment by naj1n** [comment]
@Lan-Phan Thank you for your feedback, it is extremely valuable to us. We will prioritize fixing this bug and will start work on it right away.

**Comment by naj1n** [comment]
To effectively troubleshoot and fix the bug, it would be useful for our team to have more context about what happened. If possible, could you supply sample data or additional details that might help us investigate the root cause? The more information you can provide the better, but any you can offer would be helpful.

**Comment by Lan-Phan** [comment]
Hi @naj1n ,

You can use this simple db to test:

```
postgres://ubbazdtz:mtD9qLSwj0J4dHrmek1lTKob65NZF7xr@tiny.db.elephantsql.com/ubbazdtz
```

It's a public db on elephantsql which contains 1 simple table test with 2 rows

Some queries I uses. Noted that I think null value can be available on any column with datatype has null type and from aggregation method like my #2.

1. ```select null``` -> panic, show page 500 error
2. ```select min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end) from test;``` -> panic, show page 500 error
3. ```select * from test``` -> illa returns wrong data (data_str has uuid type is converted to array, id=2 has data_str value wrong):

* illa returns:
```
[
  {
    "data_str": [
      169,
      205,
      73,
      87,
      119,
      251,
      79,
      82,
      178,
      15,
      236,
      86,
      31,
      49,
      73,
      132
    ],
    "data_timestamp": "2023-02-17T17:13:29.371312Z",
    "id": 1
  },
  {
    "data_str": [
      169,
      205,
      73,
      87,
      119,
      251,
      79,
      82,
      178,
      15,
      236,
      86,
      31,
      49,
      73,
      132
    ],
    "data_timestamp": "2023-02-17T17:13:29.371312Z",
    "id": 2
  }
]
```

* sql returns:
```
id	data_str	data_timestamp
1	a9cd4957-77fb-4f52-b20f-ec561f314984	2023-02-17 17:13:29 +0000
2		2023-02-17 17:14:20 +0000

```

**Comment by naj1n** [comment]
We will accelerate fixing this bug.

**Comment by naj1n** [comment]
We've fixed this issue with the PR(#130). The latest version of the product (accessible via [illa cli](https://github.com/illacloud/illa)) contains this fix, as well as new features such as user management. However, it is not compatible with older releases. Please upgrade to the latest version to take advantage of the fix and new features, but be aware that upgrading will prevent backwards compatibility with earlier versions.

**Comment by Lan-Phan** [comment]
Thank @naj1n , I'll check it 

Seems we still don't apply this on illa cloud (fast-try...)? quick check on that still got problem

**Comment by naj1n** [comment]
The fast-try website displays an older version of ILLA Builder. The latest version is incompatible with the website in its current form, so the fast-try site has not yet been upgraded to the latest release. For access to the newest features, you can either self-host the latest ILLA Builder release or sign up for an invitation code to use the cloud-based service which does have the latest compatible version. The invitation code to access the cloud service can be obtained on our [discord](https://discord.gg/illacloud) server.

**Comment by Lan-Phan** [comment]
Hello,

Below is new result:
1. ```select null;``` illa returns:
```
[
  {
    "?column?": null
  }
]
```

2. ```select min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end) from test;``` illa returns:

```
[
  {
    "min": null
  }
]
```

3. ```select * from test;``` illa returns

```
[
  {
    "data_str": "a9cd4957-77fb-4f52-b20f-ec561f314984",
    "data_timestamp": "2023-02-17T17:13:29.371312Z",
    "id": 1
  },
  {
    "data_str": null,
    "data_timestamp": "2023-02-17T17:14:20.876665Z",
    "id": 2
  }
]
```

It works well now.

But 1 small thing I wonder is the default name "?column?" in the first response, it seems it'll get the exactly name like that, so that I tries 2 new queries below:

4. ```select null, null;```, illa returns:

```
[
  {
    "?column?": null
  }
]
```

5. ```select null as abc, null as def;```, illa returns:

```
[
  {
    "abc": null,
    "def": null
  }
]
```

You can see that returns of query #4 is the same with query #1, but if we give name for each column, we have the new return in query #5.
--> I think this is a minor bug, we should define new distinct name for column like "?column1?", "?column2?" ...

**Comment by Lan-Phan** [comment]
the default name also causes bug for query #2 if we changes it a little bit:

```
select min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end), min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end) from test;
```

illa returns

```
[
  {
    "min": null
  }
]
```

while I expects there must be 2 fields returned
-> all generated name for columns should have serial numerical number suffix?

**Comment by karminski** [comment]
@Lan-Phan Hi, the duplicate field name will cover the key of the result struct, like:

```json
{
    "key1": 12
}
``` 

then we have an another key: 

```json
{
    "key1": 14
}
``` 

They both have the same name. The ```key1:14``` will cover the ```key1:12```. 

And if we rename the duplicate field, ***it will mismatch the database query result***.

e.g. return is:

```json
[
  {
    "?column1?": null,
    "?column2?": null
  }
]
···

Both the "?column1?" and  "?column2?" are not defined in the raw query. It can caused the context mismatch. 

Or we should hava an common rename rules for this. Then the filed prefix method should be discussed and investigated.

So I think the best way to solve this issue for now we can alias the field name like:

```sql
select min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end) as r1, min(case when data_str = 'a9cd4957-77fb-4f52-b20f-ec561f314985' THEN data_timestamp end) as r2 from test;
```

Then, the result will be like:
```json
[
  {
    "r1": null,
    "r2": null
  }
]
```

**Comment by Lan-Phan** [comment]
Hi @karminski

I doesn't understand your use-case about "the duplicate field name will cover the key of the result struct". AFAIK, we're talking about duplicated key names due to sql query doesn't explicitly state name for its column, is it right? 

When I try running ```select null, null;``` in 1 sql client, I got 2 columns as expected with same name "?column?":

<img width="358" alt="Screenshot 2023-03-01 at 8 38 06 AM" src="https://user-images.githubusercontent.com/106818620/222022809-38885a25-3f35-4c39-aa71-cccde0e15e73.png">

However, I think duplicated name "?column?" here is for visualization only because sql doesn't allow duplicated name, if we continue to try new query like ``` select * from (select null, null); ```, we'll got error:

<img width="746" alt="Screenshot 2023-03-01 at 8 52 49 AM" src="https://user-images.githubusercontent.com/106818620/222024606-8ecc13cd-e692-47c8-b9c7-637ce3fa04e9.png">


I think we can have 2 approaches to fix this:
1. Doesn't allow to have duplicated column name, including implicit names, and suggest user to add alias to fix it
2. As we use json format, we must deal with this and all implicit names (generated names) must be unique. Don't worry because if we have consistent rule for this name, user is able to guess and use it correctly. The rule I suggest: ``` <default name> <serial numerical number> ```

**Comment by karminski** [comment]
Apologies for the delayed feedback. We have recently completed a comprehensive database action refactor, and I am pleased to inform you that we now fully support this issue. 

You can now effortlessly execute SQL queries like so:

```sql
select null, null, null, null
```

The action will produce a duplicated field with renamed column names:

```json
[
  {
    "?column?_0": null,
    "?column?_1": null,
    "?column?_2": null,
    "?column?_3": null
  }
]
```

This feature is supported by all SQL actions.

**Comment by karminski** [comment]
closed due to no response
